#!/bin/sh
set -e

: "${MATRIX_DOMAIN:?MATRIX_DOMAIN missing in .env}"
: "${RTC_DOMAIN:?RTC_DOMAIN missing in .env}"

export MATRIX_SERVER_NAME="${MATRIX_SERVER_NAME:-$MATRIX_DOMAIN}"
export ELEMENT_CALL_FEATURE_USE_DEVICE_SESSION_MEMBER_EVENTS="${ELEMENT_CALL_FEATURE_USE_DEVICE_SESSION_MEMBER_EVENTS:-true}"
export ELEMENT_CALL_RTC_WAIT_FOR_KEY_ROTATION_MS="${ELEMENT_CALL_RTC_WAIT_FOR_KEY_ROTATION_MS:-3000}"
export ELEMENT_CALL_RTC_MEMBERSHIP_EVENT_EXPIRY_MS="${ELEMENT_CALL_RTC_MEMBERSHIP_EVENT_EXPIRY_MS:-180000000}"
export ELEMENT_CALL_RTC_DELAYED_LEAVE_EVENT_DELAY_MS="${ELEMENT_CALL_RTC_DELAYED_LEAVE_EVENT_DELAY_MS:-18000}"
export ELEMENT_CALL_RTC_DELAYED_LEAVE_EVENT_RESTART_MS="${ELEMENT_CALL_RTC_DELAYED_LEAVE_EVENT_RESTART_MS:-4000}"
export ELEMENT_CALL_NETWORK_ERROR_RETRY_MS="${ELEMENT_CALL_NETWORK_ERROR_RETRY_MS:-100}"

TPL=/templates/element-call-config.json.template
if [ ! -f "$TPL" ]; then
	echo "element-call-init: нет файла $TPL" >&2
	exit 1
fi

apk add --no-cache gettext >/dev/null
mkdir -p /data
umask 022
envsubst < "$TPL" > /data/element-call-config.json
chmod 644 /data/element-call-config.json
